Feature->Develop | Task 7829 update elevated button icon
webreinvent/vaahflutter pull request #32
Opened 2023-10-27 11:46 UTC by we-kislay-k001

[Task #7829 - 2023-10-21- Flutter > Training > My Training > Practice > Textable](url)
https://team.webreinvent.com/backend/collab/project/training/tasks/7829

**Time invested:** 01:00 | **Billable**: 01:00 | **Non-Billable**: 00:00

**Problem Statement**

**Describe The Fix/ Solution You Implemented**
1. I have altered class ButtonElevatedIcon docs in vaah-docs that describes to disable border according to user choice.

**Proof of your testing (Demo link or video links or image links)**
- For all the platforms
http://img-v5.getdemo.dev/screenshot/qemu-system-x86_64_heo9nfVvKa.mp4

**Dependencies**
Updated:
- 
Added:
- 

### Merge Request Checklist

- [x] I have performed a self-review of my code
- [x] My code does follow `industry standards`
- [x] My code doesn't produce `warnings/ errors` for `dart analyzer`
- [ ] New and existing `tests` pass locally with my changes (No tests are there as of now)
- [ ] The code modified as part of this PR has been covered with tests
- [x] My code is `properly formatted`
- [x] I've followed the proper naming conventions
- [ ] I have rebased the `feature` on the latest `develop`
- [ ] I have run `flutter run` after the rebase
- [ ] I have added new dependencies/ updated old dependencies
- [x] I have read all the `comments` & `notes` in `wireframe` and verified that I did take care of that
- [ ] verify that the `UI` must match with `design` & `wireframe` if available
- [ ] I have updated the `version/ build` (`x.x.x+xxx`)
- [ ] I've verified that the latest commit of `develop` exists in your `feature` branch after rebase.
- [x] My fix achieves 100% of what is required
- [x] Can enhance the solution in the future because better implementation could be made

2023-10-27 13:08 UTC, we-prajapati-c001 requested changes

2023-11-01 05:41 UTC, we-prajapati-c001 approved these changes

2024-04-22 08:38 UTC, we-prajapati-c001 commented
@we-khushal-y001 Let's handle this one now, raise a ticket in trello board and assign it to @we-kislay-k001

2024-04-22 09:41 UTC, we-khushal-y001 approved these changes

2024-05-21 07:36 UTC, merged