Feature -> Develop | Added Platform Channel Service
webreinvent/vaahflutter pull request #44
Opened 2024-07-06 06:17 UTC by we-mohd-i001

[Task #28 - Platform Specific Code > Method Channel & Event Channel](https://team.webreinvent.com/backend/collab/project/vaahflutter-service-bell/tasks/28)

**Time invested:** hh:mm format 18:20 | **Billable**: 18:20 | **Non-Billable**: 00:00

**Problem Statement**
1. The VaahFlutter doesn't have the option to use the Platform channels to establish communication between the native and Flutter side using Method and Event channels.

**Describe The Fix/ Solution You Implemented**
I have added a service that can used to invoke methods and get event streams from the native side.

**Proof of your testing (Demo link or video links or image links)**
- For Android
[Demo](https://img-v1.dev.getdemo.dev/screenshot/qemu-system-x86_64_KsrkOJ4o06.mp4)

**Dependencies**
Updated:
Added:

### Merge Request Checklist

- [x] I have performed a self-review of my code
- [x] My code does follow `industry standards`
- [x] My code doesn't produce `warnings/ errors` for `dart analyzer`
- [ ] New and existing `tests` pass locally with my changes (No tests are there as of now)
- [ ] The code modified as part of this PR has been covered with tests
- [x] My code is `properly formatted`
- [x] I've followed the proper naming conventions
- [x] I have rebased the `feature` on the latest `develop`
- [x] I have run `flutter run` after the rebase
- [ ] I have added new dependencies/ updated old dependencies
- [ ] I have read all the `comments` & `notes` in `wireframe` and verified that I did take care of that
- [ ] verify that the `UI` must match with `design` & `wireframe` if available
- [ ] I have updated the `version/ build` (`x.x.x+xxx`)
- [x] I've verified that the latest commit of `develop` exists in your `feature` branch after rebase.
- [x] My fix achieves 100% of what is required
- [x] Can enhance the solution in the future because better implementation could be made

2024-10-23 10:23 UTC, we-prajapati-c001 commented
Handing this over to @we-kislay-k001 from @we-mohd-i001

2025-03-10 13:16 UTC, we-lokesh-m001 requested changes

2025-03-10 13:16 UTC, we-lokesh-m001 commented on android/app/src/main/kotlin/com/webreinvent/vaahflutter/MainActivity.kt
> +        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
The `MethodChannel `setup logic should be abstracted into a separate function as this interface is an entry point for configureFlutterEngine

2025-03-10 13:16 UTC, we-lokesh-m001 commented on assets/env/production.json
> +  "method_channel_name": "",
Noticing a difference in method_channel configurations between `develop.json` and `production.json `method_channel_map is an object in one, while method_channel_name is a string in the other. Just wanted to check if this is intentional else we should fix it.

2025-03-10 13:16 UTC, we-lokesh-m001 commented on assets/env/staging.json
> +  "method_channel_name": "",
Noticing a difference in method_channel configurations between develop.json and production.json method_channel_map is an object in one, while method_channel_name is a string in the other. Just wanted to check if this is intentional else we should fix it.

2025-03-10 13:16 UTC, we-lokesh-m001 commented on lib/views/pages/home.dart
> +      final String? result = await _platform.invokeMethod<String>('showSnackbar');
we could use file to keep track of methods like - PlatformMethods.showSnackbar for known methods while allowing users to call any method name as a string, instead of hard-coding it.

2025-03-10 13:30 UTC, we-md-s001 commented on lib/views/pages/home.dart
> +      final String? result = await _platform.invokeMethod<String>('showSnackbar');
done

2025-03-10 13:30 UTC, we-md-s001 commented on assets/env/staging.json
> +  "method_channel_name": "",
done

2025-03-10 13:33 UTC, we-md-s001 commented on android/app/src/main/kotlin/com/webreinvent/vaahflutter/MainActivity.kt
> +        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
This code is for testing only. Once approved by all devs, it will be removed, as VaahFlutter users will write the native code themselves. I left it intentionally to help you understand my implementation.

2025-03-12 06:43 UTC, we-md-s001 commented on assets/env/production.json
> +  "method_channel_name": "",
done

2025-08-11 06:21 UTC, closed without merging